### ISSUE TITLE
Unusual Initializer Range default

### ISSUE THREAD

**Issue by evanatyourservice** [young-geng/EasyLM#114]
Hello @young-geng! Thank you for this concise and easily hackable repo!

Unfortunately I spent days wondering what was weird about training before I found the default init value is 1.0. I think a suitable value would be 0.02? Would be happy to submit a pull request! 1.0 is too unusual to be the default, and as 0.02 is so common elsewhere, I think it is hard to find the problem is the init because it's assumed it wouldn't be so different to begin with.

**Comment by young-geng** [comment]
Thanks for discovering this. Let me apply a fix.

**Comment by young-geng** [comment]
Fixed in [this commit](https://github.com/young-geng/EasyLM/commit/fe5b2c354e25d697fce7cd225e23bbbe72570da3). The correct initialization range should be relative to the model size (variance scales with input dimension).

**Comment by evanatyourservice** [comment]
Thank you!
