### ISSUE TITLE
difference between 13b v1 and v2 weight diffs + GPU requirements

### ISSUE THREAD

**Issue by jpollard-cs** [young-geng/EasyLM#17]
first of all I would like to sincerely thank you for providing the model weight diffs

this is just in time for a tool I'm literally planning to start building tomorrow which is intended to increase accessibility of technical material for folks with disabilities

would you mind sharing some information as to what the differences are between version 1 and version 2 of the model weight diffs?

also are you able to provide any details on memory + GPU requirements for running each model for inference? [here is a spreadsheet](https://docs.google.com/spreadsheets/d/1EsRZcsvbITBCfb5N1toir5huomZxIq4lDNwQW3NfPRE/edit#gid=0) ([related thread](https://github.com/facebookresearch/llama/issues/79)) someone made for LLaMa if this helps?

**Comment by young-geng** [comment]
v2 is a slightly better model than v1 (which is what we currently have on our demo). Regarding GPU requirement for inference, I think the requirement will be the same as LLaMA. For example, It requires around 30gb VRAM to run the 13b model.
