### ISSUE TITLE
Conda install slow

### ISSUE THREAD

**Issue by abdulfatir** [young-geng/EasyLM#20]
Hi!

First, thank you for this great repository. I noticed that conda takes a long time to examine conflicts and solve the environment. I was wondering if it would be better to include a `setup.py` and use `pip install -e .` instead. This would be much faster and won't require modifying the system `PYTHONPATH` (`export PYTHONPATH="${PWD}:$PYTHONPATH"`).

**Comment by young-geng** [comment]
It would be difficult to handle all the dependencies via pip, as with pip you'll need to manually install the right version of CUDA toolkit and cuDNN and set up environment variables for them.
