### ISSUE TITLE
Checksum for recovered models?

### ISSUE THREAD

**Issue by koreyou** [young-geng/EasyLM#21]
Hello and thank you for setting up an excellent repo!
I was wondering if you can provide checksum (say md5sum) for models that was recovered from the original LLaMa weights and the diff file?
(I am especially interested in Koala)
This way, people can be confident that they have managed to recover a sane model.

Thanks!

**Comment by young-geng** [comment]
This might be difficult as the floating point value of the recovered checkpoint depend on the specific library version and hardware platform. Although these differences mostly likely will not affect model performance, they can certainly make the checksum value different.
