### ISSUE TITLE
Can save_checkpoint support writing to a GCS path?

### ISSUE THREAD

**Issue by joytianya** [young-geng/EasyLM#25]
https://github.com/young-geng/EasyLM/blob/main/EasyLM/checkpoint.py#L91
Can save_checkpoint support writing to a GCS path?

**Comment by young-geng** [comment]
Yes, it does. You can just provide a `gs://` path to load or save from GCS

**Comment by joytianya** [comment]
I tried using a GCS path, but found that there were only pkl files under the GCS path and streaming_params were not saved. When I used a local path, both pkl files and streaming_params were saved. Could you please help me see where the problem is?
LOG_DIR=gs://xxx/xxx
LOG_DIR=/path/to/local/

--logger.output_dir=${LOG_DIR}

**Comment by young-geng** [comment]
Good observation! The logger module from mlxu uses `gcs_output_dir` for configuring the checkpoint dir. I'll fix this in the next version to consistently use `output_dir` to represent the file output directory on both local file system and GCS.
