### ISSUE TITLE
Code for fine-tuning?

### ISSUE THREAD

**Issue by milsun** [young-geng/EasyLM#31]
Hey, awesome work! Thanks for sharing such amazing work with us all.

Can you provide/guide fine-tuning script as can use for our own data, in a multi-gpu setup, in possible, preferably with hf?

**Comment by young-geng** [comment]
You can check out the [LLaMA documentation](https://github.com/young-geng/EasyLM/blob/main/docs/llama.md) for details about how to fine-tune any LLaMA model.

**Comment by milsun** [comment]
Thanks!
