### ISSUE TITLE
optimizer.accumulate_ gradient_ steps Will the related changes to this configuration increase the usage of graphics memory?

### ISSUE THREAD

**Issue by joytianya** [young-geng/EasyLM#36]
for llama 7b on tpu v3-8,
when --optimizer.accumulate_gradient_steps=1, it is normal, 
but --optimizer.accumulate_gradient_steps=2, it occurs oom
optimizer.accumulate_ gradient_ steps Will the related changes to this configuration increase the usage of graphics memory?
Do you have any good solutions？
```python
python3 -m EasyLM.models.llama.llama_train
 --mp_mesh_dim='4,1'
--optimizer.accumulate_gradient_steps=1
--fsdp=True 
 ...
```

```shell
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: XLA:TPU compile permanent error. Ran out of memory in memory space hbm. Used 23.43G of 15.48G hbm. Exceeded hbm capacity by 7.95G.

```

**Comment by young-geng** [comment]
Gradient accumulation requires extra memory to store the accumulated gradient, which has the same size as the parameters.
