### ISSUE TITLE
Because during training, I saw that the code added a starting character like <s> in the first position. Should we also add this character during inference to maintain consistency with training?

### ISSUE THREAD

**Issue by joytianya** [young-geng/EasyLM#41]
Because during training, I saw that the code added a starting character like
```python
<s> 
```
in the first position. Should we also add this character during inference to maintain consistency with training?

**Comment by young-geng** [comment]
Usually this is not too important when you have prompts so either way is fine.

**Comment by joytianya** [comment]
But some of the models I trained, whether or not they include <s> during inference has a significant impact on the results. What do you think could be the reason for this?

The json format of the training data is 
{"input": "user:xxxx\ngpt:", "output": "yyyy"}

train scripts is
```
...
--train_dataset.text_processor.fields='[input],output' \
--train_dataset.text_processor.add_eos_token=True \
...
```

**Comment by young-geng** [comment]
Ideally, the BOS token should be added at the test time to match the training time. Maybe some models are not very sensitive so it it okay either way. If your model is sensitive to this, I think adding the BOS token during inference would be a good idea.

**Comment by joytianya** [comment]
ok， thank you~
