### ISSUE TITLE
Do you provide an API ?

### ISSUE THREAD

**Issue by prog-amateur2** [young-geng/EasyLM#46]
hello, I just learned about your super AI Koala through the media and if I understood that it was possible to try Koala locally (with 128GB RAM, according to one of the discussion topics ! ), I was wondering if you propose an API like ChatGPT for example? 

Indeed on Linux, there is an application called [Bavarder](https://github.com/Bavarder/Bavarder/issues/17), in flatpak format, which allows to consult some AI of this type, and I thought it would be really nice to be able to use a really open source and unrestricted AI. 
Thanks a lot for your feedback.

**Comment by young-geng** [comment]
We do have JSON API endpoints in this codebase, check out the [serving documentation](https://github.com/young-geng/EasyLM/blob/main/docs/serving.md) for details. You can use these endpoints to query the model in various ways.
