### ISSUE TITLE
How you handle the attention mask for dataset chunk?

### ISSUE THREAD

**Issue by waterhorse1** [young-geng/EasyLM#47]
Hi,

I find that in the following code, easylm processes the dataset by taking chunks. From my understanding, it might make different documents in the same chunk. For example, the first document might take 512 tokens while the second documents take 128 tokens in a chunk of 640 tokens. In this case, I think the generation for the second document should not see the first document, so we might need to use attention mask to mask that. But I don't see any related code in easylm, so I am wondering how you handle the attention mask for this problem.

https://github.com/young-geng/EasyLM/blob/18375bd571edbe1e3ee340cedd0b9c7379645aed/EasyLM/data.py#L158-L183

**Comment by young-geng** [comment]
This way of processing is called sequence packing, and indeed the model can attend to the previous example in some cases. In practice, prior works that use this technique such as PaLM did not find any negative effect for attending occasionally to previous example, so we follow the same convention here.

**Comment by waterhorse1** [comment]
Thank you for your answer! It helps a lot!
