### ISSUE TITLE
Model serving example

### ISSUE THREAD

**Issue by congyingxia** [young-geng/EasyLM#49]
Hi,

Thanks for the amazing repo. I am trying to serve local models then do the evaluation. But I can only find related classes implemented in serving.py. Can you give some examples about how to initialize the classes, call the functions and serve the model?

Thanks a lot!

**Comment by young-geng** [comment]
For LLaMA model, you can find the serving documentation [here](https://github.com/young-geng/EasyLM/blob/main/docs/llama.md#serving-llama).
