### ISSUE TITLE
Strategies for handling large corpora through Google Cloud Storage?

### ISSUE THREAD

**Issue by Beomi** [young-geng/EasyLM#5]
Hi!
I have recently come across this repository and have been conducting tests using TPUv4 pods. 

As part of my experimentation, I have explored several approaches for feeding datasets into the model, 
including utilizing Hugging Face datasets or employing JSON files (with lines) either locally or through a GCS bucket.

During my analysis, 
I have noticed that the JSON data loader appears to download the entire JSON file from the gs:// directory and subsequently tokenize and yield the line-by-line data. 
This approach presents a challenge when dealing with corpus files exceeding 1TB in size, as it is not practical to store such extensive data in a single JSON file.

I am curious to learn how do you handle this issue,
and I would appreciate any insights!

Thanks for your great work 👍

**Comment by young-geng** [comment]
The [JSONDataset](https://github.com/young-geng/EasyLM/blob/0526e32851af6293483fdd6c6dd5f49850b8a5ac/EasyLM/data/pretrain_data.py#L187) from this repo already implements streaming from GCS bucket if you give a path of gs:// for the json file. For the huggingface dataset, I've tried implementing something similar but it seems that the huggingface datasets library does not support streaming from a bucket file system.

**Comment by Beomi** [comment]
Hello, and thank you so much for your prompt response. I apologize for any confusion caused by my previous question.

I would like to share my current situation: I have thousands of JSONL files, each with a size of approximately 1GB. It appears that the JSON dataset currently supports only a single JSON file.

Could you kindly offer your thoughts on the best approach to handle these files? Would it be more efficient to concatenate all of the files into a single, large JSON file, or should we consider implementing a new method to support a glob path (e.g., 'gs://~~~/*.jsonl')?

Thank you again for your assistance, and I'm looking forward to your valuable suggestions.

**Comment by young-geng** [comment]
I'd recommend just joining the files together. Since each example is a line in the file, simply concatenating the files should suffice.

**Comment by redbrain** [comment]
What's the best way to handle extremely large datasets from HuggingFace (ie RedPajama) with TPU v4 Pod?

My current thought is to use a separate VM to save the dataset to a persistent disk, then mount the disk read-only to the pod and output the model to a GCS bucket. However, I have no clue whether that would work.

I'm guessing you've done this before (since open-llama was trained with EasyLM and RedPajama). How did you accomplish it?

**Comment by young-geng** [comment]
Why not directly reading the data from GCS? EasyLM supports directly reading data from GCS buckets when a GCS path is passed into the dataloader.

**Comment by redbrain** [comment]
Reading the dataset docs, it wasn't clear that HuggingFace datasets were compatible with GCS (or if they were, how one would go about setting it up)

**Comment by young-geng** [comment]
The huggingface one is not, but json one is, and that's how you load custom datasets.
