### ISSUE TITLE
Recommended setup given a v4-512?

### ISSUE THREAD

**Issue by OhadRubin** [young-geng/EasyLM#55]
Hey,
If I understand correctly, you trained using a v4-512.
Can you share how you configured your node and what sizes?
Thanks!
Ohad

**Comment by young-geng** [comment]
Thanks for your interest in our project. The optimal configuration depends on your model size. For instance, for a small model like 7B and 13B, you might want to use only fully sharded data parallelism (FSDP), as FSDP can overlap communication and computation better than tensor parallelism.

For our configuration for OpenLLaMA 7B, we use 64 way FSDP, and leave the rest for normal data parallelism. So the mesh shape configuration is `--mesh_dim='1,-1,1'`.
