### ISSUE TITLE
Is there a plan to support Falcon?

### ISSUE THREAD

**Issue by joytianya** [young-geng/EasyLM#57]
Is there a plan to support [Falcon](https://huggingface.co/tiiuae/falcon-7b)
Considering the better performance of Falcon on [OpenLLM leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard), would you consider supporting Falcon?
Thank you~

**Comment by young-geng** [comment]
Unfortunately that's not one of our priorities right now.
