### ISSUE TITLE
LLaMA Training

### ISSUE THREAD

**Issue by wimjan123** [young-geng/EasyLM#6]
Hi!

First of all: thanks for your amazing repo. It's pretty easy to use, even for someone that doesn't have an ML/Python background like me. 

I am, however, struggling to use it in training LLaMA on a TPU.
Can you maybe give a short step by step guide? 
Like for example: Which weights should I load as checkpoint? The original one from Meta, the Huggingface or the JAX weights, and if so, how do I convert the original from Meta to JAX?

**Comment by young-geng** [comment]
I'm working on the documentation for training and I'll release it in a few days. Stay tuned!

**Comment by wimjan123** [comment]
Awesome! If you need any help with testing etc, let me know. I have some TPUv4 quota :)

**Comment by young-geng** [comment]
I've updated the documentations for fine-tuning LLaMA. Let me know if you encounter any problems training and serving LLaMA.

**Comment by wimjan123** [comment]
Lmao 'few days' was more like a few hours. Awesome! One thing I'm missing (as a newbie to LLM training) in the docs is: Where can I set the output of my trained model? Can I use the --logger.gcs_output_dir flag?

**Comment by young-geng** [comment]
The output dir is the same as the logger, so it is `logger.gcs_output_dir`, if that was set, otherwise `logger.output_dir`.

**Comment by wimjan123** [comment]
Everything seems to be working, but is it true that LLaMA conversion script converts it to float32? I tried multiple things but whenever I start training it says: 
{'accuracy': ShardedDeviceArray(0.30334473, dtype=**float32**),
 'gradient_norm': ShardedDeviceArray(126.99751, dtype=**float32**),
 'learning_rate': ShardedDeviceArray(5.000271e-06, dtype=**float32**, weak_type=True),
 'loss': ShardedDeviceArray(5.60371, dtype=**float32**),
 'param_norm': ShardedDeviceArray(2515.4229, dtype=**float32**),
 'step': 0}
 
 This makes training on TPU very slow.

**Comment by young-geng** [comment]
All the training are indeed in FP32 for numerical stability. However [JAX does matmul with bf16 internally](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.matmul.html), so there's no performance loss on TPUs or modern GPUs.

**Comment by young-geng** [comment]
Not exactly sure, as I don't have access to TPU-v4s right now. As far as I know, v4-32 will give you 16 devices in JAX (the two cores per chip are viewed as one logical core), so 16,1 is probably optimal. What batch size are you using?

**Comment by wimjan123** [comment]
That's supposed to be the "accumulate_gradient_steps" flag right? It's set to 32

**Comment by young-geng** [comment]
Not quite. That one is for gradient accumulation. The batch size is configured in the dataset module.

**Comment by wimjan123** [comment]
I tried experimenting with higher settings, but anything higher than 8 and it runs out of memory. When training gpt-j i get about 1 second per iteration. Will expriment further and let you know.

**Comment by Beomi** [comment]
I'm currently testing llama model and here's my config for 7B LLAMA model:

- Device: TPUv4-64 (=32 visible cores)
- Seq len 2048 (I'll double check later, may be it could be 1024)
- batch size 8
- MP: (2,1)

It works smoothly without OOM error.
