### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by syzymon** [young-geng/EasyLM#67]
Hi, we are immensely grateful for the release of the codebase, which enabled us to fine-tune LLaMA in JAX. Is there a standardized way to cite this repo in a paper?

**Comment by young-geng** [comment]
I'm glad to hear that you find it useful for your research. You can use the following bibtex:

```
@software{geng2023easylm,
  author = {Geng, Xinyang},
  title = {EasyLM: A Simple And Scalable Training Framework for Large Language Models},
  month = March,
  year = 2023,
  url = {https://github.com/young-geng/EasyLM}
}
```
