### ISSUE TITLE
Anyone tries to train with gpt-j?

### ISSUE THREAD

**Issue by Taekyoon** [young-geng/EasyLM#69]
I'm planning to train gpt-j using tpu v2 resource.
Hoping that I can initiate PR for training gpt-j.

**Comment by young-geng** [comment]
I've trained GPT-J a while ago and it should work. Are you encountering any issues?

**Comment by Taekyoon** [comment]
No, I could not find guidelines for training gpt-j, so I just made this issue.
I'll make another issue if some issues come up :) 

Thanks!
