### ISSUE TITLE
What precision strategy is used in pre-training OpenLlama?

### ISSUE THREAD

**Issue by haozhouamzn** [young-geng/EasyLM#71]
Hello.

I am wondering what kind of precision strategy is applied during the pre-training of OpemLlama?

Is it fp32, fp16, bf16 or mixed precision?

Thank you in advance

**Comment by young-geng** [comment]
We used `dtype='fp32'`, since for small models using `fp16` does not give much speed improvement

**Comment by haozhouamzn** [comment]
Thanks Young. Just to confirm, it's using fp32 for all three models (3B, 7B and 13B)?

**Comment by young-geng** [comment]
It was fp32 for all of them
