### ISSUE TITLE
Config file to train openllama 7B v2

### ISSUE THREAD

**Issue by yhcc** [young-geng/EasyLM#73]
Thanks for release openllama 7Bv2, I am wondering whether this example script is the script you used to train it 
https://github.com/young-geng/EasyLM/blob/main/examples/pretrain_llama_7b.sh

**Comment by yhcc** [comment]
Thanks for you replay. I have another questions on the OpenLLaMA V2 training, thanks for your patience in advance. Did you apply extra cleaning on these data splits, or just used these dataset as it is.

**Comment by young-geng** [comment]
We didn't apply any extra cleaning. We simply combined the dataset and shuffled the examples.
