### ISSUE TITLE
Script for SFT? 

### ISSUE THREAD

**Issue by alitirmizi23** [young-geng/EasyLM#8]
First of all, thanks for the great work! 
could you point me to the SFT script? It might sound silly, But I fail to find it anywhere.

**Comment by young-geng** [comment]
The script for fine-tuning largely follows the [LLaMA](https://github.com/young-geng/EasyLM/blob/main/docs/llama.md) documentation. You can start from there.

**Comment by alitirmizi23** [comment]
Ok thanks. Does SFT  work by generating outputs token by token as in the usual way LLMs are trained to generate following a prompt or does it differ?

**Comment by young-geng** [comment]
EasyLM supports fine-tuning in both ways. You can choose to apply or not apply loss in any part of the sequence. Check out the [dataset documentation](https://github.com/young-geng/EasyLM/blob/main/docs/dataset.md).
