### ISSUE TITLE
Windows gpu_environment.yml

### ISSUE THREAD

**Issue by thekevshow** [young-geng/EasyLM#9]
Appears there is issue running this in windows? Getting the following error 

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - jaxlib==0.3.15[build=*cuda*]
  - pytorch-cpu=1.13.0
  
I will likely wrap this up in a docker container in the meantime.

**Comment by young-geng** [comment]
Unfortunately, I don't have a windows machine to test the compatibility with windows. Maybe this can work with WSL2?

**Comment by zangjunhao** [comment]
I have the same problem

**Comment by MichaelMartinez** [comment]
I was able to install the conda env in WSL2 without problem and convert standard llama into EasyLM format. I ran out of RAM while recovering diffs.

**Comment by andresdelcampo** [comment]
This seems to have worked for me -warning, somewhat advanced- . 

Create a conda environment directly, then install packages separately:
```
conda create -n EasyLM -python=3.8 -y
conda activate EasyLM
```
Some packages are problematic:
Replace pytorch-cpu with torch

Install these packages separately like this:
```
pip install jax==0.3.16 https://whls.blob.core.windows.net/unstable/cuda111/jaxlib-0.3.7+cuda11.cudnn82-cp38-none-win_amd64.whl
conda install -c nvidia cudatoolkit=11.3
conda install -c nvidia cuda-nvcc=11.3
conda install -c nvidia cudnn
```

Then create a requirements.txt with
```
numpy
scipy
numba
h5py
matplotlib
scikit-learn
jupyter
tqdm
jax == 0.3.16
sentencepiece
torch == 1.13.0
flax == 0.6.0
optax == 0.1.3
chex == 0.1.5
distrax == 0.1.2
orbax == 0.0.23
transformers == 4.27.2
huggingface_hub == 0.13.3
datasets == 2.9.0
einops
tensorflow == 2.11.0
dill
seaborn
absl-py
gtimer
joblib
wandb == 0.13.5
ml_collections
gcsfs == 2022.11.0
requests
jupyter_http_over_ws
lm-eval == 0.3.0
mlxu == 0.1.9
pydantic
fastapi
uvicorn
gradio
```
and run it with 
`pip install -r requirements.txt`

I am not 100% sure it will all work, but at least installs all now.
